const data = {
  products: [
    {
      //_id: "1",
      name: "Sketcher-01",
      slug: "sketcher01",
      category: "Swimsuits",
      image: "/images/p1.jpg",
      price: 1200,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      //_id: "2",
      name: "Sketcher-02",
      slug: "sketcher02",
      category: "Swimsuits",
      image: "/images/p2.jpg",
      price: 800,
      countInStock: 0,
      brand: "Nike",
      rating: 5,
      numReviews: 6,
      description: "high quality shirt",
    },
    {
      //_id: "3",
      name: "Sketcher-03",
      slug: "sketcher03",
      category: "Swimsuits",
      image: "/images/p3.jpg",
      price: 1200,
      countInStock: 5,
      brand: "Nike",
      rating: 3,
      numReviews: 12,
      description: "high quality shirt",
    },
    {
      //_id: "4",
      name: "Sketcher-04",
      slug: "sketcher04",
      category: "Swimsuits",
      image: "/images/b1.jpg",
      price: 1450,
      countInStock: 0,
      brand: "Nike",
      rating: 4,
      numReviews: 8,
      description: "high quality shirt",
    },
    {
      //_id: "5",
      name: "Sketcher-05",
      slug: "sketcher05",
      category: "Swimsuits",
      image: "/images/b2.jpg",
      price: 1300,
      countInStock: 8,
      brand: "Nike",
      rating: 3.5,
      numReviews: 15,
      description: "high quality shirt",
    },
    {
      //_id: "6",
      name: "Sketcher-06",
      slug: "sketcher06",
      category: "Swimsuits",
      image: "/images/b3.jpg",
      price: 1500,
      countInStock: 3,
      brand: "Nike",
      rating: 4.8,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      //_id: "7",
      name: "Sketcher-07",
      slug: "sketcher07",
      category: "Swimsuits",
      image: "/images/g1.jpg",
      price: 1450,
      countInStock: 0,
      brand: "Nike",
      rating: 4,
      numReviews: 8,
      description: "high quality shirt",
    },
    {
      //_id: "8",
      name: "Sketcher-08",
      slug: "sketcher08",
      category: "Swimsuits",
      image: "/images/g2.jpg",
      price: 1300,
      countInStock: 8,
      brand: "Nike",
      rating: 3.5,
      numReviews: 15,
      description: "high quality shirt",
    },
    {
      //_id: "9",
      name: "Sketcher-09",
      slug: "sketcher09",
      category: "Swimsuits",
      image: "/images/g3.jpg",
      price: 1500,
      countInStock: 3,
      brand: "Nike",
      rating: 4.8,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};


module.exports = data;