const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/1.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/2.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/3.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/4.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/5.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Swimsuits",
      image: "/images/6.jpg",
      price: 35,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};


module.exports=data;